# Add your Python code here
import random
def run_program():
    # Your program logic goes here
    output = "English language Question Paper"
    return output
def grammer_gear():
    g_questions = [
        ["Underline the subjects in these sentences that state facts about whales.",
                ["Whales are creatures of the open sea.", "There are many types of whales in the oceans.",
                 "The blue whale is the largest animal on earth.", "The tongue of the blue whale weighs as much as an elephant.",
                 "The humpback whale is known for its magical songs.", "The fin whale is known as the greyhound of the sea.",
                 "All winter, they can live without food.", "The grey whale can travel day and night, up to 120 kilometers."]],

        ["Add suitable subjects to these sentences. Make sure you use a mix of pronouns, nouns and noun phrases.",
                ["—---------- keep us warm in winter.",
                 "—----------- like to write only for children.",
                 "—----------- only for me?",
                 "—----------- were awakened by the fire alarm.",
                 "—----------- are participating in the quiz.",
                 "—----------- was from an unknown number.",
                 "Has —----------- delivered your gift?",
                 "—---------- are very talented.",
                 "—--------- advised us to visit the Udayagiri and Khandagiri caves.",
                 "—------------ teaches us aerobics."]],

        ["Underline the predicates in these sentences about cartoons.",
                ["Cartoons are popular among both children and adults.",
                "Many cartoon characters have been created by Walt Disney.",
                "To many children, Bugs Bunny is a top favourite cartoon character.",
                 "In 1928, Walt Disney created Mickey Mouse.",
                "At first, Mickey Mouse was created in black and white.",
                 "Superman is widely watched on television.",
                "Tom and Jerry make the funniest cartoon pair ever.",
                 "Winnie-the-Pooh is a bear, always in a red shirt.",
                 "The brown-coloured Scooby Doo does not really want to work.",
                 "Dora is always in the company of her monkey."]],

        ["Add suitable predicates to these subjects.",
                ["The greengrocer —------------------------------------------",
                 "The alert pilot land —------------------------------------------",
                 "The astronauts —------------------------------------------",
                 "My mother and father —------------------------------------------",
                 "My school library —------------------------------------------",
                 "They —------------------------------------------",
                 "Her broken ankle —------------------------------------------",
                 "The man-eating tiger —------------------------------------------",
                 "The Indian flag —------------------------------------------",
                 "Nandini —------------------------------------------"]],

        ["Underline the objects in these sentences.",
                 ["Mr. Thomas teaches us Mathematics.",
                  "The tourists watched the Light and Sound Show.",
                  "The designer is designing a new dress.",
                  "Mina could not solve the puzzle.",
                  "My friends speak English.",
                  "The monkeys are eating bananas.",
                  "The children loved the cheesecake.",
                  "The baby pandas were rolling on the grass.",
                  "Books open the world to us.",
                  "I washed, dried and ironed my clothes."]],

        ["Add suitable objects to these sentences.",
                 ["My grandmother shares —-----------------------------",
                  "This doctor gives —--------------------",
                  "The vet treated —----------------",
                  "The champion won —-----------------------------",
                  "Newspapers report —-----------------------------",
                  "The archer shot the —-----------------------------",
                  "The lifeguard at the pool saved —-----------------------------",
                  "The architect designed —-----------------------------",
                  "My coach taught me —-----------------------------",
                  "My musician friend has composed —-----------------------------"]],

        ["Use these phrases in sentences to add meaning to them.",
                 ["the leftover food —-------------------------",
                  "across the road —-------------------------",
                  "running all the way —-------------------------",
                  "an interesting story —-------------------------",
                  "with yellow flowers —-------------------------",
                  "while parking —-------------------------",
                  "in the darkness —-------------------------",
                  "of tea and biscuits —-------------------------",
                  "an unkind word —-------------------------",
                  "at the sports club —-------------------------"]],

        ["Write whether the underlined groups of words are phrases (P) or clauses (C).",
                 ["This storybook is available in most bookstores.",
                  "My sister is preparing for her performance.",
                  "I can see the stars as the sky is very clear.",
                  "He plays all day as if he has no work.",
                  "Dancing in the rain is real fun.",
                  "My father drives his car at a very steady speed.",
                  "Those people in fancy dresses are going for a party.",
                  "They are eating greedily because they have not eaten for days.",
                  "Rani and I get along as we both share similar interests.",
                  "The dog howled all night outside my gate."]],

        ["How many clauses are there in each sentence? Underline them separately",
                 ["He joined in late, but he was not sorry.",
                  "The bakery smelt of fresh cakes and biscuits.",
                  "Father looked tired, yet he cooked dinner.",
                  "Join the dots to draw a dinosaur.",
                  "Dad pulled out the trunk, and a mouse sprang out.",
                  "They all were happy, for the holidays had started.",
                  "I keep my nails trimmed.",
                  "My mother works as a photographer, while my father is a teacher.",
                  "Sudip does not like reading novels, nor does he read short stories.",
                  "My brother loves to solve crosswords."]],

        ["Add another clause to complete each sentence. Remember to add a subject and a predicate.",
                 ["Shiva has not come to school today, for —-----------------------",
                  "Let us leave immediately or —-----------------------",
                  "The house has just been painted, yet —-----------------------",
                  "I will sketch the landscape and —-----------------------",
                  "The rain has stopped, but —-----------------------",
                  "The grass looks greener there, but —-----------------------",
                  "She is so short, yet —----------------------",
                  "The man has no manners, nor —---------------------",
                  "My father forgot to get my book, so —-----------------------",
                  "You must reach the bus stand, or —-----------------------"]],

        ["Read these simple sentences about popular tales. Underline the subject and circle the verb.",
                 ["Rapunzel had magnificent long hair.",
                  "Cinderella left the ballroom at the stroke of midnight.",
                  "Snow White and Rose Red were fond of each other.",
                  "The tortoise and the hare ran a race.",
                  "Goldilocks has golden-coloured hair.",
                  "The fairies take Peter Pan to Neverland.",
                  "The ugly duckling grew up into a beautiful swan.",
                  "Hansel and Gretel outsmart a witch to escape.",
                  "The big bad wolf blew down the house made of straw.",
                  "Beauty and the Beast became good friends."]],

        ["Underline the subjects in these sentences about popular fables. Then, write S for simple sentences and C for compound sentences.",
                 ["Ants work hard and save for a rainy day.",
                  "One bowl was made of bronze, and the other bowl was earthen.",
                  "The mouse was weak and small, yet it helped a big lion.",
                  "The grateful mouse chewed through the net and set the lion free.",
                  "The fox saw grapes hanging from the vine.",
                  "Freddie Fox tricked the goat, and she jumped into the well.",
                  "Denzil Donkey tried to be a dog but knocked his master down.",
                  "A lion and a fox went hunting together.",
                  "The king was worried a lion would kill his son, so he kept him in captivity.",
                  "The young prince punched the wall and hurt himself."]],

        ["Write these pairs of sentences as compound sentences using the conjunctions in brackets.",
                 ["I did not call. She did not call. (nor)",
                  "Joy is honest. Joy is polite too. (and)",
                  "Dad was upset. I had lost the car key. (for)",
                  "I reached on time. The train was late. (but)",
                  "You may attend painting classes. You may join the theatre group. (or)",
                  "My grandfather is old. He is regular with his walks. (yet)",
                  "I was cheered. I was also given an award. (and)",
                  "The pans are not washed. The plates are not washed. (nor)",
                  "I am not well. I am going to school. (yet)",
                  "Betty, Vinny, and Henu are going for a camp. They are packing. (so)"]],

        ["Write these compound sentences as two simple sentences.",
                 ["Dogs make good pets, as they are very loyal.",
                  "I really want to play, but the doctor says I must rest.",
                  "The car ran out of petrol, so we had to park it.",
                  "I spoke well, but Della was better than me.",
                  "The sun may be bright in the hills, yet it is pleasant there.",
                  "We have never been to the hills, nor have we seen the sea.",
                  "Should I start the song, or will you take the lead?",
                  "Mona and Jay are good friends, yet they quarrel a lot.",
                  "The spectators should reach early, or they will not get good seats.",
                  "There was no money at home, nor was the bank open."]],

        ["Rewrite this passage using suitable conjunctions (for, and, nor, but, or, yet, so). The pairs of sentences to be combined have been numbered.",
                 ["The three friends-Norah, Manik, and Gina-went for a walk by the lake. Their dog Banjo too went along.",
                  "The friends chose a quiet place by the lake. They started playing marbles.",
                  "Suddenly, the friends turned their heads. There was a loud splash!",
                  "They saw something splashing in the water. They could not make out what. Where was Banjo?",
                  "Banjo was missing. Norah ran towards the lake.",
                  " Manik and Gina ran behind her. Norah suddenly stopped.",
                  "Banjo had not drowned. Dogs can swim in the water."]],

        ["Underline the subject in each sentence. Write D if it is the doer or R if it is the receiver of the action.",
                 ["Our gardener is growing flowers.",
                  "My sister bought a crossword book for me.",
                  "The cheese has been nibbled by the mouse.",
                  "Parents love their children.",
                  "Some children donate their toys.",
                  "These fruits were picked by us.",
                  "Roosters and crows make the most noise.",
                  "The criminals were punished by the police.",
                  "Apples are grown in Himachal Pradesh.",
                  "The tourists made a big snowman."]],

        ["Read these historical facts. Write A for those in active voice and P for those in passive voice. And change the voice",
                 ["Shah Jahan built the Red Fort in Delhi.",
                  "The Sanchi Stupa is surrounded by four gateways.",
                  "Many historical monuments have been declared heritage sites.",
                  "The India Gate was designed by the famous British architect.",
                  "Santiniketan in West Bengal was set up by Rabindranath Tagore.",
                  "Sir Malcolm Hailey developed the Jim Corbett National Park in Nainital.",
                  "Many tourists visit the Mysore Palace.",
                  "The Ellora Caves were carved out of volcanic deposits.",
                  "The Taj Mahal in Agra is made of white marble.",
                  "The chariot shape of the Konark Sun Temple attracts many tourists."]],

        ["Underline the verbs in active voice and rewrite the sentences in passive voice.",
                 ["I clean my room every day.",
                  "The teacher asked a question.",
                  "The students wrote the answers.",
                  "My sister was baking a cake in the morning.",
                  "The school has announced a holiday.",
                  "They have mowed the lawn.",
                  "My aunt is knitting a sweater for me.",
                  "I am packing the gift.",
                  "The mechanic fixed the car.",
                  "The blind woman had crossed the road on her own."]],

        ["Underline the verbs in passive voice and circle the doers of the action. Then, rewrite the sentences in active voice.",
                 ["The window was pushed open by the wind.",
                  "The grass has been eaten by the goats.",
                  "This neat circle has been drawn by a small child.",
                  "Food was served by my father to the guests.",
                  "We were guided by the map in the forest.",
                  "The stray dogs are fed by the kind lady.",
                  "Money was collected by the students for the poor.",
                  "Gold ornaments are sold by a jeweler.",
                  "Buildings are designed by architects.",
                  "A gold medal had been won by Meeta last year."]],

        ["Write five imperative sentences in active voice. The first one has been donefor you.",
                 ["Close the door."]],

        ["Tick the sentences that are in indirect speech. And change them into direct speech",
                 ['Rohan said, "I was late, so I missed the bus."',
                  'The man said, "There is a fly in my soup!"',
                  "The boy said he would never lie again.",
                  'The man said to his son, "You must sleep on time."',
                  "The baker said to me that he sold only freshly baked bread.",
                  "The trainer says that she is the best.",
                  'She said, "I was listening to my favourite songs."',
                  "The old woman requested me to share the seat with her.",
                  "The banker asked my father to sign the cheque again.",
                  'They said, "We will cheer for our country."']],

        ["Complete these sentences in indirect speech with suitable reporting verbs.",
                 ["Silvy —------------ (offered / cried) to help her father wash the car.",
                  "The principal —------------ (cried / announced) that it would be a holiday on Monday.",
                  "Meha —------------ (suggested/ cried) that she had spilled her cold coffee.",
                  "The teacher —------------ (told / explained) to me how angles are measured.",
                  "I —------------ (offered/requested) my mother to help me iron my uniform.",
                  "The crowd —------------  (shouted / complained) that they had won the match.",
                  "The guard —------------ (said / told) us that the museum would close at 6 p.m.",
                  "The children —------------ (requested/ complained) that was not what they wanted to eat.",
                  "The man —------------ (offered / complained) that he had not received his package till then.",
                  "The driver —------------ (said / told) that we were not very far from the city."]],

        ["Punctuate these sentences in direct speech and change them to indirect speech",
                 ["The lady said to my mother your daughter sings melodiously. ",
                  "Mona said to Tina I can easily finish your lunch.",
                  "The children said we trapped a rat and then let it go",
                  "The Principal said you have put up an excellent show.",
                  "I said to my sister I am suspicious of the stranger.",
                  "Dad said to me you should not share personal information with everyone.",
                  "The farmer said my family works with me in the field.",
                  "The teacher said I want you all to avoid careless mistakes.",
                  "I said to Farhan I like your hairstyle.",
                  "The guide said we will be visiting the most beautiful monument of our country."]],

        ["Complete these sentences with phrasal verbs formed from the verbs in brackets. Make the necessary changes in the verb form.",
                 ["—------------- (Look) for speed breakers on the road!",
                  "You must —-------------  (take) your shoes before centering the room.",
                  "Keya —-------------  (call) an urgent meeting to discuss the picnic.",
                  "—---------- (look) the traffic bulletin before you start.",
                  "Mehak —---------- (break) on hearing that she had not made it to the finals.",
                  "The teacher asked us to —--------------- (take) the important points.",
                  "Rohan was asked to —--------- (call) the school office for fee details.",
                  "Everyone says I —---------- (take) my father in looks.",
                  "The entire school —---------- (look) to the annual spring festival.",
                  "The match had to be —---------- (call) due to bad weather.",
                  "The plane taxied before —--------- (take).",
                  "I often —---------- (look) the meanings of words in the dictionary.",
                  "They were late because their car had —------------ (break) on the way.",
                  "Mom advised me to —---------- (break) from the group of cheaters."]],

        ["Choose another synonym from the box for each list of words. Respectful, thrilling, impartial, humorous, charitable, gorgeous, litter, sickly, attentive, guarded",
                 ["Hilarious, amusing, comical",
                  "Trash, waste, garbage",
                  "Polite, courteous, gracious,",
                  "Unhealthy, ill, diseased",
                  "Safe, protected, secure",
                  "Exciting, lively, dramatic",
                  "Fair, equal, honest",
                  "Charming, beautiful, splendid",
                  "Generous, benevolent, unselfish",
                  "Careful, thorough, alert"]],

        ["Complete these sentences with antonyms from the box for the words in brackets. appreciate, worried, ancient, expensive, build, peace, peak, truth, rare, display",
                 ["Kavya bought an —----------- (cheap) dress for her anniversary.",
                  "We sighted some —---------- (common) birds in the sanctuary.",
                  "Everybody will —------- (criticise) your sincere efforts to make peace.",
                  "There is so much —----------- (chaos) in the hills, unlike in the cities.",
                  "The Egyptian pyramids are some of the most —--------- (modern) monuments in the world.",
                  "The shop windows  —----------- (conceal) their best products.",
                  "The princess was keen to know the —--------- (myth) of her secret powers.",
                  "India is keen to —-------- (destroy) good relations with the countries of the world.",
                  "The player is at the —-------- (bottom) of his performance in this Test series.",
                  "The farmer was always —---------- (relaxed) about his idle son."]],

        ["Now form the opposites of these words by adding the prefix in-, ir- or il-.",
                 ["Legal",
                  "active",
                  "Responsible",
                  "literate",
                  "Regular",
                  "reparable",
                  "direct",
                  "visible",
                  "sufficient",
                  "Legible"]],

        ["Now form adjectives from these nouns by adding the suffixes -ly, -al or -ous. You may have to change the spellings of some words.",
                 ["Day",
                  "Person",
                  "Magic",
                  "Victory",
                  "Poison",
                  "Monster",
                  "cost",
                  "Universe",
                  "Nerve",
                  "mystery"]],

        ["Write down the meaning of the following phrases",
                 ["under the weather",
                  "fair-weather friend",
                  "raining cats and dogs",
                  "come rain or shine",
                  "save for a rainy day",
                  "it never rains but it pours",
                  "snowed under",
                  "Be on cloud nine",
                  "Storm in a teacup",
                  "get wind of (something)"]],

        ["Now try to use these expressions to complete these sentences by making the necessary changes.",
                 ["The farmer had saved some of his earnings —-----------------------",
                  "I cannot miss this competition —-----------------------------",
                  "I have been —------------ because of a severe cold",
                  "My father is —--------------- as there is an inspection next week.",
                  "The Indian football team was —------------ after the victory.",
                  "The argument was just —--------------------- and nothing serious.",
                  "If Mom —------------------ of my plans to celebrate her birthday, there will be no surprise left.",
                  "The trip has been called off as it has been —------------------ since morning.",
                  "It is truly said —---------------------- as today all things have been going wrong for me.",
                  "Harsh came to know his —---------------------------- when they put the blame on him."]],

        ["Fill in the blanks with appropriate prepositions.",
                 ["We were asked to take our seat —---------- the mats.",
                  "Water collected —--------- the bridge due to heavy rain.",
                  "We have a five-minute break —----------- each class.",
                  "We have been living in this locality —-------- 2005.",
                  "The nurse sat —----------- the ailing patient, looking after him all night.",
                  "There is a cricket academy —------------- our school.",
                  "Mom will be busy with meetings —---------- 5 p.m.",
                  "We walked —---------------- the seashore collecting seashells all the way."]],

        ["Circle one noun phrase and underline one adjective phrase in these sentences.",
                 ["The yellow and green sweater has been knitted by my grandmother.",
                  "The pizzas in this outlet are amazingly delicious.",
                  "The TV in my brother's room was frightfully expensive.",
                  "The boy in the jumpsuit offered to help the frail little lady cross the road.",
                  "The new movie on aliens was barely entertaining.",
                  "Ekta's aunt made a beautiful canvas oil painting. ",
                  "The short man narrated a fairly ridiculous story.",
                  "The smell in a tannery is awfully repulsive."]],

        ["Circle the subject and underline the predicate in these sentences. ",
                 ["The planets revolve around the sun always.",
                  "The monkeys are plucking bananas from the trees and eating them.",
                  "The tigers are actively hunting down sheep on the hills these days. ",
                  "Mangoes, apples and watermelons are the sweetest fruits.",
                  "She has been the most successful female Indian tennis player.",
                  "The students of class six are going to Ajmer on an educational trip.",
                  "My classmate Mohit plays for the school basketball team.",
                  "My uncle and aunt have applied for an Australian visa."]],

        ["Rewrite these sentences in passive voice.",
                 ["The hunters killed a wild boar.",
                  "The teacher counseled the girls who were late to class.",
                  "Rohit won the gold medal on the School Sports Day.",
                  "The director is releasing his new movie.",
                  "The carpenter is repairing the sofa seats.",
                  "A kind man brought the injured puppy to the vet.",
                  "He caught a very difficult catch in the last match.",
                  "The cobbler repaired my shoes in minutes."]],

        ["Write these compound sentences as two simple sentences.",
                 ["Malik confessed his lie, and he also apologized to his parents.",
                  "Rhea climbed onto the stage and gave a brilliant performance.",
                  "Rishabh bought a new car but it got stolen after a week.",
                  "There was a lot of disturbance, for the plane was flying through the clouds.",
                  "The old lady did not recognise me, so I had to remind her who I was. ",
                  "John missed the flight, for he was stuck in traffic.",
                  "Jenny missed the train, so she could not make it to the meeting in time.",
                  "Simi has not reached the station, nor has Nancy."]],
        ["Rewrite these sentences in indirect speech.",
                 ['Maya said, "I am busy on a call."',
                  '"Finish your homework before you switch on the TV," said my mother rather sternly.',
                  'The lady said to the fruit seller, "Whose orchard are these apples from?"',
                  '"There is a cockroach in the bathroom," screamed my little sister.',
                  '"Do not walk on the grass," said the gardener.',
                  '"When is your car insurance renewal due?" said the policeman.',
                  '"You are late to school," said the prefect.',
                  'The boy said, "I can run faster than a cheetah."']],

        ["Circle the object of the verb in each sentence.",
                 ["The tourists took many pictures of the waterfall. ",
                  "The man was releasing balloons of all colours.",
                  "Pigeons build nests in niches in houses.",
                  "The dancers at the Republic Day Parade wore colourful dresses.",
                  "The family distributed lots of sweets among the poor on the festival day.",
                  "I asked his address on phone.",
                  "My mother coaches the basketball team in my school.",
                  "The artists will exhibit their paintings on Children's Day."]],
        ["Use a noun phrase as a subject to complete each sentence.",
                 ["—------------ disturbed the quiet night.",
                  "—------------- is your birthday present.",
                  "—------------- has a fresh collection of books.",
                  "—------------- should be allowed to enter first.",
                  "—------------- are very comfortable in this theatre.",
                  "—------------- are trained gymnasts.",
                  "—------------- are seen holding their medals in this picture.",
                  "—------------- are some animals of interest to me."]],

        ["Use a noun phrase as an object to complete these sentences.",
                 ["The bright sun lit up —-------------.",
                  "The school choir sang —--------------.",
                  "The birds collected —------------------- to build their nest.",
                  "The great oak tree spread —------------- and sheltered the villagers from the summer sun.",
                  "The gurgling river washed away —-------------- as it flowed downstream.",
                  "The lion saw —-------------- in the village well.",
                  "The rich merchant gathered —---------------- in the city.",
                  "The honest driver returned —--------------- of his passenger."]]

    ]

    selected_list = (random.choices(g_questions, k=10))
    return selected_list


def complete_english():
    c_question = [
        ["Spelling months of the year and days of the week;",
                 ["bottomless pit (ab)",
                  "cannot be reached (inac)",
                  "growing old (ag)",
                  "pleasant (ag)",
                  "to hospital in an amb_____",
                  "bullets (am)",
                  "North Pole (A)",
                  "climbing-ap____tus",
                  "nearly or roughly (ap)",
                  "he draws building-plans (a)"]],

        ["Write the abstract nouns which tell us the qualities or state of these people (like wise men: wisdom):",
                 ["stupid vandals",
                  "rogues",
                  "proud parents",
                  "active athletes",
                  "slaves",
                  "flattering courtiers",
                  "loyal subjects",
                  "persevering workers"]],

        ["Show in phrases or sentences the difference in meaning when we form the plural of these words:",
                 ["force",
                  "down",
                  "work",
                  "compass",
                  "manner",
                  "look",
                  "custom",
                  "spirit",
                  "spectacle"]],

        ["Write correctly:",
                 ["the (better, best) of these two",
                  "faster than (I, me)",
                  "the clever player in the whole team",
                  "a prize for the (hardworking) pupil."]],

        ["Form verbs by adding prefixes or suffixes:",
                 ["friend",
                  "courage",
                  "little captive",
                  "glory",
                  "terror",
                  "start",
                  "large",
                  "fat",
                  "wide"]],

        ["I, me  Complete these phrases:",
                 ["Let you and ___",
                  "between you and ____",
                  "you and ___ will",
                  "as old as _____",
                  "give to you and ____",
                  "chase you and ____."]],

        ["Form a compound word from each of these words, then state what part of speech each new word is:",
                 ["green",
                  "sea",
                  "sky",
                  "eyed",
                  "black",
                  "eagle",
                  "police",
                  "fire",
                  "son",
                  "dust",
                  "blue."]],

        ["Write (i) synonyms (ii) antonyms of:",
                 ["shout",
                  "discover",
                  "pull",
                  "happy",
                  "dead",
                  "appear",
                  "approximately",
                  "expensive",
                  "gloomy",
                  "grab",
                  "trivial"]],

        ["Put in prepositions:",
                 ["Different _____ yours,",
                  "Aim ______ my work, ",
                  "Equal ______ the target, ",
                  "Averse ______ hard work, ",
                  "Comment _____ my work,",
                  "Equal ______ that,",
                  "Free _____ infection,",
                  "Meddle _____ it,",
                  "Rely ____ you,,",
                  "Write _______ you _______ something important."]],

        ["Complete these similes: ",
                 ["as slippery as _____ ; ",
                  "as light as ______ ; ",
                  "as green as _______; ",
                  "strong like ________; ",
                  "as dead as ________;",
                  "plump like ________"]],

        ["Find out all the meanings of the following",
                 ["trap",
                  "shaft",
                  "tarry",
                  "inclined",
                  "mole",
                  "dot",
                  "land",
                  "dust",
                  "cold",
                  "mind",
                  "relish",
                  "shift"]],

        ["Write phrases to show the difference in meaning: ",
                 ["announce, pronounce; ",
                  "resemble, dissemble;",
                  "broadness, breadth; ",
                  "session, cession;",
                  "stationery, stationary;",
                  "course, coarse;",
                  "complimentary, complementary;",
                  "council, counsel;",
                  "council, counsel;"]],

        ["Spelling",
                 ["a railway coach (c)",
                  "now above your head (c)",
                  "basement (c)",
                  "graveyard (c)",
                  "tea",
                  "cof—",
                  "co—",
                  "too proud (con)",
                  "usual (cus)",
                  "full of zeal (enth)",
                  "well known (fam)",
                  "liked best of all (fav)",
                  "above the eyebrows (f)",
                  "rules of language (gra)"]],

        ["What is the plural of the following",
                 ["court-martial, ",
                  "looker-on, ",
                  "onlooker, ",
                  "handful, ",
                  "son-in-law, ",
                  "daughter-in-law,",
                  "plateau, ",
                  "scissors, ",
                  "deer, ",
                  "measles, ",
                  "grouse (2 meanings), ",
                  "cannon"]],

        ["Think of adjectives meaning 'most___'",
                 ["anger, ",
                  "happiness, ",
                  "brightness, ",
                  "heat"]],

        ["Write the past and perfect tenses: ",
                 ["be, ",
                  "bear, ",
                  "broadcast, ",
                  "burst, ",
                  "deal,",
                  "dig, ",
                  "do, ",
                  "eat, ",
                  "lay,",
                  "lie, ",
                  "sew, ",
                  "wake"]],

        ["Spelling ei or ie:",
                 [" N..1, ",
                  "bel. .f, r. .n, ",
                  "br. .f, rec..pt, ",
                  "w..gh, ",
                  "f. .ld, ",
                  "v. .l, ",
                  "conc..t, ",
                  "dec..t, ",
                  "handkerch..f, ",
                  "h..ght, ",
                  "w..r, ",
                  "h..ress, ",
                  "r..gn, ",
                  "f..rce"]],

        [" Add the suffixes us or ous:",
                 ["geni_________, ",
                  "jeal____, ",
                  "foc______, ",
                  "phosphor_____, ",
                  "fung_____, ",
                  "wonder, ",
                  "rigour, ",
                  "thunder, ",
                  "miracle, ",
                  "monster"]],

        ["Write abbreviations:",
                 ["Fire Hydrant, ",
                  "Great Britain, ",
                  "television, ",
                  "Street, ",
                  "Saint, ",
                  "Professor, ",
                  "Captain"]],

        ["What do these abbreviations stand for:",
                 ["C.S.E., ",
                  "G.C.E., ",
                  "U.S.A., ",
                  "U.S.S.R., ",
                  "Ave., ",
                  "B.R.; ",
                  "E.R. II, ",
                  "G.P., ",
                  "U.K., ",
                  "flu, ",
                  "gym, ",
                  "phone"]],

        [" Put in prepositions:",
                 ["tired _____ listening to your chatter, ",
                  "decide ____ a date for the gala, ",
                  "sympathise _____  you ______ your troubles, ",
                  "suffer _______ asthma, ",
                  "an anorak similar ______ yours, ",
                  "fell out ______ a tree, ",
                  "different yours, ",
                  "disappointed ______ you."]],

        ["Choose the correct words:",
                 ["(i) (possible, probable) We must decide on a date for the Sports, not just a  ____ one. ",
                  "(ii) (practice, practise) There will be a netball _____ at 4 o'clock to _____ shooting. ",
                  "(iii) (you, I, me) ____ and _____ must leave now. Let ____ and _____ both try to win."]],

        ["Form comparative and superlative degrees:",
                 ["extraordinary, ",
                  "irrational, ",
                  "odd, ",
                  "low, ",
                  "quiet, ",
                  "strange, ",
                  "loose, ",
                  "great, ",
                  "violent, ",
                  "narrow, ",
                  "rough, ",
                  "hot, ",
                  "grey, ",
                  "busy, ",
                  "bad."]],

        [" Write (i) synonyms (ii) antonyms of:",
                 ["extraordinary, ",
                  "irrational, ",
                  "headlong, ",
                  "odd, ",
                  "quiet, ",
                  "enormous, ",
                  "terrible, ",
                  "past, ",
                  "narrow, ",
                  "rough"]],

        ["Make compound words from",
                 ["eye, ",
                  "flash, ",
                  "hand, ",
                  "foot, ",
                  "men, ",
                  "door",
                  "Find five compound words, like spyhole, in 'Escape'"]],

        ["Spelling nouns from:",
                 ["abstain, ",
                  "accept, ",
                  "accessible, ",
                  "accidentally, ",
                  "accompanying, ",
                  "accumulate, ",
                  "achieve, ",
                  "acquit, ",
                  "aggravate, ",
                  "aggressive, ",
                  "allotted, ",
                  "annoyed"]],

        ["Write the plural of",
                 ["calf, ",
                  "echo, ",
                  "loss, ",
                  "grass, ",
                  "quiz, ",
                  "sash, ",
                  "wax, ",
                  "wolf, ",
                  "folio, ",
                  "halo, ",
                  "torpedo, ",
                  "cliff, ",
                  "reef, ",
                  "proof, ",
                  "half"]],

        ["the usual small flock of sheep",
                 ["What collective nouns fit these: fowls, flowers, puppies, soldiers, birds, cows, warships, fruit trees (apple; orange; lemon)?",
                  "What are the masculine, feminine and young of sheep?",
                  "What are sheep-folds, shepherds, sheep-dip, sheepdogs, shearing?",
                  "What are the masculine and feminine gender of horse, foal, cattle, swan, ass, sparrow, roedeer, elephant, fox, goat?"]],

        ["Sandy froze into stillness.",
                 ["Write the past, past continuous and perfect tenses: freeze, arise, bind, build, cling, dream, fling, go, grow, keep."]],

        ["Write correctly:",
                 ["Whwhats your name james asked the new boy",
                  "martin he replied whats yours",
                  "come here shouted the policeman whats your game",
                  "the boys told the policeman they were doing nothing i dont believe you he said"]],

        ["Write the abbreviation of:",
                 ["Colonel, ",
                  "Post Office, ",
                  "Intelligence Quotient, ",
                  "Master of Arts, ",
                  "photograph, ",
                  "aeroplane, ",
                  "Wiltshire, ",
                  "Berkshire, ",
                  "Hertfordshire,",
                  "who will,",
                  "she is"]]

    ]

    selected_list = (random.choices(c_question, k=5))
    return selected_list


# if __name__ == "__main__":
#     output = run_program()
#     print(output)  # This will print the output to the console


# g = grammer_gear()
# # print(b)
# selected_list = (random.choices(g, k = 10))
# print(selected_list)

def show(selected_list):
    for i in selected_list:
        # print(i[0])
        num = "*"
        print(f"{num})", i[0])
        for n in i[1]:
            print(i[1].index(n)+1, n)
        print("\n")


def informal_letter():
    print("*) Informal Letter")
    letter = ["A letter to the Editor of a newspaper describing the problem of noise pollution in your area",
              "A letter to the Editor of a newspaper mentioning the problem of mosquito menace due to stagnant water",
              "A letter to the Editor of a newspaper describing poor condition of roads in your locality"]
    selected_list = (random.choices(letter, k=1))
    print(selected_list[0])
    print("\n")

def composition():
    print("*) Composition")
    composition = ["Importance of sports",
                  "Life Before and After the Internet",
                  "Natural disasters in Bangladesh",
                  "Independence Day of Bangladesh",
                  "Patriotism"]

    selected_list = (random.choices(composition, k=1))
    print(selected_list[0])
    print("\n")


show(grammer_gear())
show(complete_english())
informal_letter()
composition()



